# Generated by Django 3.0.8 on 2020-08-02 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pairwise', '0002_auto_20200801_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='script',
            old_name='rsme_in_set',
            new_name='rmse_in_set',
        ),
    ]
