# Generated by Django 3.1 on 2020-08-09 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pairwise', '0003_auto_20200802_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='cor_est_to_actual',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='wini',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Lesser'), (1, 'Greater')], verbose_name='is left lesser or greater?'),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='winj',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Lesser'), (1, 'Greater')], verbose_name='is right lesser or greater?'),
        ),
    ]
