# Generated by Django 3.1 on 2020-08-09 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pairwise', '0004_auto_20200808_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparison',
            name='set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pairwise.set', verbose_name='the set to which this comparison belongs'),
            preserve_default=False,
        ),
    ]
