# Generated by Django 3.1 on 2020-08-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pairwise', '0006_auto_20200809_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparison',
            name='resulting_set_corr',
            field=models.FloatField(default=0, verbose_name='storing the resulting correlation of set est param to actual'),
        ),
    ]
