# Generated by Django 3.1 on 2020-08-19 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pairwise', '0007_comparison_resulting_set_corr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='set',
            old_name='user',
            new_name='owner',
        ),
    ]
