# Generated by Django 3.1 on 2020-08-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pairwise', '0008_auto_20200818_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='fisher_info',
            field=models.FloatField(default=0, verbose_name='Fisher information for MLE of parameter based on comparison data'),
        ),
        migrations.AddField(
            model_name='script',
            name='lo_hi95ci',
            field=models.FloatField(default=0, verbose_name='@phi; log odds high 95% confidence interval'),
        ),
        migrations.AddField(
            model_name='script',
            name='lo_lo95ci',
            field=models.FloatField(default=0, verbose_name='@phi; log odds low 95% confidence interval'),
        ),
        migrations.AlterField(
            model_name='script',
            name='estimated_parameter_in_set',
            field=models.FloatField(default=0, verbose_name='MLE of parameter from comparisons of this script'),
        ),
        migrations.AlterField(
            model_name='script',
            name='lo_of_win_in_set',
            field=models.FloatField(default=0, verbose_name='&phi; log odds of winning for this script'),
        ),
    ]
