# Generated by Django 3.1 on 2020-08-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pairwise', '0009_auto_20200826_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='se',
            field=models.FloatField(default=0, verbose_name='standard error of parameter for this script'),
        ),
    ]
