# Generated by Django 3.1 on 2020-08-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pairwise', '0011_script_stdev'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparison',
            name='decision_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparison',
            name='decision_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparison',
            name='difficulty_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comparison',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparison',
            name='interest_rating',
            field=models.IntegerField(default=3, verbose_name='how interesting the assessor found this comparison'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='uninterrupted',
            field=models.IntegerField(default=1, verbose_name='is the comparison interrupted or uninterrupted allowing valid duration computation'),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='resulting_set_corr',
            field=models.FloatField(default=0, verbose_name='computing the resulting correlation of set est param to actual'),
        ),
        migrations.AlterField(
            model_name='script',
            name='rmse_in_set',
            field=models.FloatField(default=0, verbose_name='RMSE of parameter for this script'),
        ),
    ]
