# Generated by Django 3.1 on 2020-09-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pairwise', '0013_auto_20200831_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparison',
            name='count_same_p',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='winj',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='is right lesser or greater?'),
        ),
    ]
