# Generated by Django 3.1 on 2020-09-02 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pairwise', '0015_auto_20200901_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparison',
            name='decision_end',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='decision_start',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='difficulty_rating',
            field=models.IntegerField(choices=[(0, 'Not At All Difficult'), (1, 'Not Too Difficult'), (2, 'Difficult'), (3, 'Very Difficult')], default=0, editable=False, verbose_name='how difficult is the comparison to judge?'),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='duration',
            field=models.DurationField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='interest_rating',
            field=models.IntegerField(choices=[(1, 'Not At All Interesting'), (2, 'Not Interesting'), (3, 'Neutral'), (4, 'Interesting'), (5, 'Very Interesting')], default=3, editable=False, verbose_name='how interesting is this comparison'),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='judge',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='the user judging the pair'),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='resulting_set_corr',
            field=models.FloatField(default=0, editable=False, verbose_name='computing the resulting correlation of set est param to actual'),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='uninterrupted',
            field=models.IntegerField(choices=[(1, 'Uninterrupted'), (0, 'Interrupted')], default=1, editable=False, verbose_name='is the comparison interrupted or uninterrupted allowing valid duration computation'),
        ),
        migrations.AlterField(
            model_name='script',
            name='comps_in_set',
            field=models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='count of all comparisons with this script'),
        ),
        migrations.AlterField(
            model_name='script',
            name='count_same_p',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='script',
            name='estimated_parameter_in_set',
            field=models.FloatField(default=0, editable=False, verbose_name='MLE of parameter from comparisons of this script'),
        ),
        migrations.AlterField(
            model_name='script',
            name='fisher_info',
            field=models.FloatField(default=0, editable=False, verbose_name='Fisher information for MLE of parameter based on comparison data'),
        ),
        migrations.AlterField(
            model_name='script',
            name='lo_hi95ci',
            field=models.FloatField(default=0, editable=False, verbose_name='@phi; log odds high 95% confidence interval'),
        ),
        migrations.AlterField(
            model_name='script',
            name='lo_lo95ci',
            field=models.FloatField(default=0, editable=False, verbose_name='@phi; log odds low 95% confidence interval'),
        ),
        migrations.AlterField(
            model_name='script',
            name='lo_of_win_in_set',
            field=models.FloatField(default=0, editable=False, verbose_name='&phi; log odds of winning for this script'),
        ),
        migrations.AlterField(
            model_name='script',
            name='prob_of_win_in_set',
            field=models.FloatField(default=0, editable=False, verbose_name='ratio of wins to comparisons for this script'),
        ),
        migrations.AlterField(
            model_name='script',
            name='rmse_in_set',
            field=models.FloatField(default=0, editable=False, verbose_name='RMSE of parameter for this script'),
        ),
        migrations.AlterField(
            model_name='script',
            name='se',
            field=models.FloatField(default=0, editable=False, verbose_name='standard error of parameter for this script'),
        ),
        migrations.AlterField(
            model_name='script',
            name='stdev',
            field=models.FloatField(default=0, editable=False, verbose_name='standard deviation of comps sample for this script'),
        ),
        migrations.AlterField(
            model_name='script',
            name='wins_in_set',
            field=models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='count of all comparisons in which this script wins'),
        ),
    ]
