# Generated by Django 3.1 on 2020-09-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pairwise', '0016_auto_20200902_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='greater_statement',
            field=models.TextField(default='more', verbose_name='the question posed for assessors about the items'),
        ),
        migrations.AlterField(
            model_name='script',
            name='parameter_value',
            field=models.PositiveSmallIntegerField(verbose_name='the hidden parameter value to be compared in development'),
        ),
    ]
