# Generated by Django 3.1 on 2020-09-07 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pairwise', '0019_comparison_orderby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparison',
            name='orderby',
        ),
    ]
