# Generated by Django 3.1 on 2020-12-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pairwise', '0020_remove_comparison_orderby'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='comps_display',
            field=models.FloatField(default=0, editable=False, verbose_name='1/10th count of all comparisons with this script'),
        ),
    ]
