# Generated by Django 3.1 on 2020-12-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pairwise', '0021_script_comps_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparison',
            name='average_diff_est_act',
            field=models.FloatField(default=0, editable=False, verbose_name='computing the resulting difference of set est param to actual'),
        ),
    ]
