# Generated by Django 3.1 on 2020-12-24 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pairwise', '0023_comparison_select_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparison',
            name='select_method',
            field=models.PositiveSmallIntegerField(default=1, editable=False, verbose_name='method of selecting next comparison 1=comps, 2=same-p, 3=rmse'),
        ),
    ]
