# Generated by Django 3.1 on 2020-12-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pairwise', '0024_auto_20201223_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparison',
            name='select_method',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='method of selecting next comparison 1=comps, 2=same-p, 3=rmse'),
        ),
    ]
