# Generated by Django 3.1 on 2020-12-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pairwise', '0026_auto_20201224_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='cor_est_to_actual',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
