# Generated by Django 3.1 on 2020-12-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pairwise', '0027_auto_20201224_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparison',
            name='resulting_set_corr',
            field=models.FloatField(blank=True, default=0, editable=False, null=True, verbose_name='computing the resulting correlation of set est param to actual'),
        ),
    ]
