# Generated by Django 3.1 on 2021-01-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pairwise', '0028_auto_20201224_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparison',
            name='epchangeratio',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='ratio of change in estimated parameter value of both scripts due to this comparison'),
        ),
    ]
