# Generated by Django 4.0 on 2021-12-22 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pairwise', '0029_comparison_epchangeratio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparison',
            name='average_diff_est_act',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='epchangeratio',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='resulting_set_corr',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='select_method',
        ),
        migrations.RemoveField(
            model_name='script',
            name='parameter_value',
        ),
        migrations.RemoveField(
            model_name='set',
            name='cor_est_to_actual',
        ),
    ]
