# Generated by Django 4.0 on 2021-12-28 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pairwise', '0030_remove_comparison_average_diff_est_act_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='script',
            name='image',
        ),
        migrations.AddField(
            model_name='set',
            name='judges',
            field=models.ManyToManyField(blank=True, related_name='judges', related_query_name='judge', to=settings.AUTH_USER_MODEL, verbose_name='the users who may compare this set'),
        ),
        migrations.AlterField(
            model_name='set',
            name='greater_statement',
            field=models.TextField(default='Greater', verbose_name='the question posed in a comparison'),
        ),
        migrations.AlterField(
            model_name='set',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='The user who uploaded the scripts of this set'),
        ),
    ]
